### ISSUE TITLE
check for input type

### ISSUE THREAD

**Issue by michalovadek** [staudtlex/icr#2]
thanks for this nice package. I noticed `krippalpha()` runs as expected on matrix input but not on data frames. I would in fact expect the latter to throw an error and ask the user to explicitly convert to matrix.

I'm not quite sure why in the case of the canonical data (`codings`) the alpha is the same for both the matrix and the data frame, but in most other applications this will not hold as far as I can tell.

For example:

```{r}
matrix(c("A","B","A","A","B","B","N","N"), nrow = 2) |> krippalpha()
# alpha = 0.667

matrix(c("A","B","A","A","B","B","N","N"), nrow = 2) |> as.data.frame() |> krippalpha()
# alpha = 0
```

**Comment by staudtlex** [comment]
@michalovadek, thank you very much for using `icr` and reporting the error. An updated version is on its way to CRAN

The error occurs because inside krippalpha(), `data.matrix()` performs a character->factor->integer conversion on each character column of a data frame. Factors are created by sorting alphabetically the set of unique strings in a column and assigning each string an integer (starting at 1), such that the first string (w.r.t. alphabetical order) is assigned an integer value of 1, the second string an integer value of 2 etc. Since only the _relative order_ within a column is taken into account, the generated integers do not necessarily represent the same string across all data columns.

 `codings` does not suffer from this issue as it consists of numeric data.
